### ISSUE TITLE
myIPAddress() not implemented?

### ISSUE THREAD

**Issue by DidierA** [kiron1/proxydetox#207]
Hello,

I am trying to setup proxydetox in an enterprise environment with a proxy.pac URL and kerberos authentication.
When an access is made, the follwoing error  is dumped, and the client gets an empty answer.

```
thread 'tokio-runtime-worker' panicked at 'duk error: uncaught: 'identifier \x27myIpAddress\x27 undefined''
```

A call to `myIpAddress()` is indeed used in the proxy.pac file, and if I retrieve it, store it locally and modify the pac file to use an IP value instead of calling the function, everything works correctly.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file), `myIpAddress` is a valid function to call in a PAC script. (Note: despite the warning on mdn's doc, I have tested `myIpAddress()` in a PAC file with Firefox on linux, an it returns the host's IP address, and not 127.0.0.1)

Following is  a 'dummy' .pac files that triggers the problem when used:

```javascript
function FindProxyForURL(url, host) {
var IP;
	IP = myIpAddress();
	return "DIRECT"; 
}
```
version used:
```
$ proxydetox --version
proxydetox 0.5.4 (77ae147d94)
```

full backtrace:
```
$ RUST_BACKTRACE=full proxydetox -v --negotiate --pac-file  $PWD/dummy_proxy.pac
   0.000940957s  INFO proxydetox: starting listening=127.0.0.1:3128 authenticator=negotiate pac_file=Some(Path("/home/didier/.config/proxydetox/dummy_proxy.pac"))
   6.026342977s DEBUG call: proxydetox::session: new connection client_addr=127.0.0.1:57260
thread 'tokio-runtime-worker' panicked at 'duk error: uncaught: 'identifier \x27myIpAddress\x27 undefined'', duktape/src/context.rs:23:5
stack backtrace:
   0:     0x561b223a299d - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x561b223a299d - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561b223a299d - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x561b223a299d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x561b223c600c - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x561b2239d411 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x561b223a4145 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x561b223a4145 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x561b223a4145 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x561b223a3e66 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x561b223a46d6 - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:698:17
  11:     0x561b223a45c7 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
  12:     0x561b223a2e54 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x561b223a42f9 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  14:     0x561b21efc6d3 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  15:     0x561b222279a1 - duktape::context::fatal_handler::h995a414afe91a35f
  16:     0x561b2222cc13 - duk_fatal_raw
  17:     0x561b22234668 - duk_err_longjmp
  18:     0x561b2222e5cf - duk_js_execute_bytecode
  19:     0x561b2222ee75 - duk__handle_call_raw
  20:     0x561b221f22e1 - paclib::evaluator::Evaluator::find_proxy::h6a961b0e28645af4
  21:     0x561b22057282 - tokio::runtime::enter::exit::h609eb99d9de26810
  22:     0x561b2213e9b1 - tokio::runtime::thread_pool::worker::block_in_place::h0060b6cf893c3b51
  23:     0x561b220a0921 - <proxydetox::session::peer::PeerSession as tower_service::Service<http::request::Request<hyper::body::body::Body>>>::call::{{closure}}::hf182275b9f71c479
  24:     0x561b22084b0a - <tracing_futures::Instrumented<T> as core::future::future::Future>::poll::h78facaf5ebdfee8d
  25:     0x561b21f77f3d - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch::h4059bb61a8a493ee
  26:     0x561b21f4db0a - <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll::h6febeead413faad0
  27:     0x561b21fc823f - <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll::hbbfc6b9bcabbb941
  28:     0x561b21fc0717 - tokio::runtime::task::core::CoreStage<T>::poll::hd554b0916da7c473
  29:     0x561b21fdec1a - tokio::runtime::task::harness::Harness<T,S>::poll::h2ba269abf99e42be
  30:     0x561b2220ecd5 - std::thread::local::LocalKey<T>::with::h2c3e18b224732262
  31:     0x561b2220b753 - tokio::runtime::thread_pool::worker::Context::run_task::h920c710bee35ce63
  32:     0x561b2220ac6e - tokio::runtime::thread_pool::worker::Context::run::h9d3497490ee01bf0
  33:     0x561b222123a7 - tokio::macros::scoped_tls::ScopedKey<T>::set::h0378fe21fecc1a0b
  34:     0x561b2220a6c9 - tokio::runtime::thread_pool::worker::run::hd1649ff7775b926a
  35:     0x561b22221a4c - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h43739a1bc282c342
  36:     0x561b221fd989 - tokio::runtime::task::harness::Harness<T,S>::poll::h3f657d50141dfd2e
  37:     0x561b2220736a - tokio::runtime::blocking::pool::Inner::run::he3228c41f2afa905
  38:     0x561b22216342 - std::sys_common::backtrace::__rust_begin_short_backtrace::haa26257c4312576a
  39:     0x561b22216a6f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h6175b285fe97f9b8
  40:     0x561b223a75d3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1680342795a2dc08
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  41:     0x561b223a75d3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h45204a69827b0e83
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  42:     0x561b223a75d3 - std::sys::unix::thread::Thread::new::thread_start::h5d4e11bbda4161c8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/unix/thread.rs:108:17
  43:     0x7fca9b1efb43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  44:     0x7fca9b281a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  45:                0x0 - <unknown>
```

**Comment by kiron1** [comment]
Hello @DidierA,

This is correct, we didn't implement `myIpAddress()` since we did not see the use case for it. The simplest fix would be to implement `myIpAddress()` as `const myIpAddress = () => "127.0.0.1";`, but I don't know how much this would help.

**Comment by DidierA** [comment]
Hi,
thanks for the reply. Returning 127.0.0.1 does not help, as in my case the  IP is used to check which network the host belongs to, and choose a different proxy.
Moreover, the fix you added hides the problem, in my opinion a warning should be logged stating that myIpAdress() returns a fixed value.

**Comment by kiron1** [comment]
I hope this solves your problem better: #212

**Comment by DidierA** [comment]
Thanks, I will test this when I have an opportunity.

**Comment by kiron1** [comment]
Fixed with https://github.com/kiron1/proxydetox/pull/212
